import { z } from "zod";
import { PILLAR_KEYS } from "./advertis-vector";

// ── Signal Sources ─────────────────────────────────────────────────────
// OPERATOR   = human fixer / admin manual input
// RTIS       = generated by RTIS cascade protocols (R, T, I, S)
// EXTERNAL_SAAS = ingested from client's existing SaaS stack (Monday, Zoho, etc.)
// FEEDBACK   = processed from feedback-loop / feedback-processor
// METRIC     = social/media/press metrics ingestion

export const SIGNAL_SOURCES = [
  "OPERATOR",
  "RTIS",
  "EXTERNAL_SAAS",
  "FEEDBACK",
  "METRIC",
] as const;

export type SignalSource = (typeof SIGNAL_SOURCES)[number];

export const SignalSourceSchema = z.enum(SIGNAL_SOURCES);

// ── PillarSignal — canonical type for all signal producers ─────────────
// Every connector, feedback processor, RTIS protocol, and metric ingestion
// must produce PillarSignal objects. This is the single contract that feeds
// the Pillar Gateway via writePillarAndScore().

export const PillarSignalSchema = z.object({
  /** Which ADVE pillar this signal affects */
  pillarKey: z.enum(PILLAR_KEYS),

  /** Named driver within the pillar (e.g. "monday-velocity", "zoho-pipeline") */
  driver: z.string().min(1).max(128),

  /** Signal value — numeric score, text insight, or structured data */
  value: z.union([
    z.number(),
    z.string(),
    z.record(z.unknown()),
  ]),

  /** Origin of this signal */
  source: SignalSourceSchema,

  /** Confidence level 0–1. Floor enforced by source hierarchy:
   *  verified = 0.85, external_saas = 0.65, ai_estimate = 0.45 */
  confidence: z.number().min(0).max(1),

  /** External reference ID (e.g. Monday item ID, Zoho deal ID) */
  externalRef: z.string().optional(),

  /** Arbitrary metadata from the source system */
  metadata: z.record(z.unknown()).optional(),
});

export type PillarSignal = z.infer<typeof PillarSignalSchema>;

// ── Confidence floors by source ────────────────────────────────────────

export const CONFIDENCE_FLOORS: Record<SignalSource, number> = {
  OPERATOR: 0.90,
  RTIS: 0.50,
  EXTERNAL_SAAS: 0.65,
  FEEDBACK: 0.55,
  METRIC: 0.40,
};

/** Enforce minimum confidence based on source hierarchy */
export function enforceConfidenceFloor(signal: PillarSignal): PillarSignal {
  const floor = CONFIDENCE_FLOORS[signal.source];
  return {
    ...signal,
    confidence: Math.max(signal.confidence, floor),
  };
}
